services:
  db:
    image: mysql:8.0
    container_name: mysql_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: movie-api-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:root@localhost:3306/movies_db
    extra_hosts:
      - "host.docker.internal:host-gateway"